name: goodreads-reviews-analysis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8.5
  - selenium
  - pandas
  - pytest
  - beautifulsoup4
  - lxml
  - nltk
  - xlrd
  - doit
  - openpyxl
  - textblob
  - spacy
  - spacy-lookups-data
  - matplotlib
  - pip
  - pip:
    - -e .
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz